# Generated by Django 5.1.2 on 2024-11-17 10:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('pages', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
    ]
